# Generated by Django 3.1.7 on 2021-02-27 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='promoted',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=32),
        ),
    ]
