# Generated by Django 3.1.7 on 2021-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210227_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
