# Generated by Django 3.1.7 on 2021-03-06 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('auth_type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('rule_name', models.CharField(max_length=32)),
                ('data', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.authitem', to_field='name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
