# Generated by Django 3.1.7 on 2021-03-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_auto_20210306_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authitem',
            name='rule_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
